# Generated by Django 5.0 on 2024-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_usuario',
            name='usuario',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
