# Generated by Django 5.0 on 2024-01-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0002_datos_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario1', models.CharField(max_length=100000)),
                ('id_usuario2', models.CharField(max_length=100000)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
