# Generated by Django 5.0 on 2024-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0003_amigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_usuario',
            name='genero',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_usuario',
            name='nacionalidad',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
