# Generated by Django 5.0 on 2024-01-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0004_datos_usuario_genero_datos_usuario_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='datos_usuario',
            name='nacionalidad',
        ),
    ]
