# Generated by Django 5.0 on 2024-01-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0005_remove_datos_usuario_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_usuario',
            name='genero',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_usuario',
            name='nacionalidad',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
