# Generated by Django 5.0 on 2024-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0006_datos_usuario_genero_datos_usuario_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_usuario',
            name='genero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datos_usuario',
            name='nacionalidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
