# Generated by Django 5.0 on 2024-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0007_alter_datos_usuario_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='datos_usuario',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='datos_usuario',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datos_usuario',
            name='nacionality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
