# Generated by Django 5.0 on 2024-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0009_remove_datos_usuario_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_usuario',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datos_usuario',
            name='nacionality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
