# Generated by Django 5.0 on 2024-01-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0010_datos_usuario_gender_datos_usuario_nacionality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion', models.CharField(max_length=100000, null=True)),
                ('id_usuario', models.CharField(max_length=100000, null=True)),
            ],
        ),
    ]
