# Generated by Django 5.0 on 2024-01-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0011_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion', models.CharField(max_length=100000, null=True)),
                ('texto', models.CharField(max_length=100000, null=True)),
                ('id_usuario', models.CharField(max_length=100000, null=True)),
            ],
        ),
    ]
