# Generated by Django 5.0 on 2024-01-28 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0012_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
