# Generated by Django 5.0 on 2024-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0014_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='leido',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
